#define WHITE_LANE 0
#define ROAD_COLOR 1

#define VECTOR_TURN 0
#define STICK_LANE 1
#define DETECT_METHOD WHITE_LANE//ROAD_COLOR; WHITE_LANE
#define TURN_METHOD VECTOR_TURN//VECTOR_TURN; STICK_LANESTICK_LANE